name: Deploy to production

on:
    push:
        branches:
                - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout main branch
            uses: actions/checkout@v2
            with:
                    ref: main

          - name: Setup credentials
            run: |
                git config --global user.email ${{ vars.DEPLOYMENT_EMAIL }}
                git config --global user.name ${{ vars.DEPLOYMENT_USERNAME }}
                git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY    

          - name: Install dependencies
            run: npm install

          - name: Build & Deploy
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: npm run deploy
